### ISSUE TITLE
建议添加一个命令行参数"-c"手动指定配置文件的位置

### ISSUE THREAD

**Issue by meoow** [yryz/httpproxy#2]
首先，感谢编写了这个工具，之前一直用polipo做中转，还纳闷过为什么ss客户端的本地部分非得用socks5监听，就不能提供一个http的代理？我倒是琢磨过干脆自己实现一个，结果要么没时间，要么忘记了。看到你这有现成的了真是太好了。

看了一下你的config.go，配置文件硬编码到了`~/.httpproxy/config.json`。一般命令行工具除了有默认的配置文件路径以外还会提供参数让用户直接传递配置文件路径。所以我建议能加一个`-c` flag，可以让用户指定配置文件，这样也好方便做系统启动直接运行的服务。

**Comment by yryz** [comment]
已经支持 -c 参数 https://github.com/yryz/httpproxy/commit/2918a326d40fabe41f32cf4c4ab53e3228ae8add ，http代理可能是相对小众的需求吧，我也是因为开发环境需要而实现的，比如服务器、Linux上也相对好用些
