### ISSUE TITLE
HTTP 301返回会被错认为200

### ISSUE THREAD

**Issue by meoow** [yryz/httpproxy#3]
原因：

**proxy.go**文件第90行，没有把`resp, err := tr.RoundTrip(r)`中**resp**的**status**值传递给`w http.ResponseWriter`，导致返回值全是200。这样会造成比如访问http网站做301跳转https失效。

解决：

应该在107行`//copy body`的前一行添加`w.WriteHeader(resp.StatusCode)`

**Comment by yryz** [comment]
7fdcd3b2959cb07842f6f2d3e8e52dbe7d474358 已修复，thks
