### ISSUE TITLE
似乎有内存泄露

### ISSUE THREAD

**Issue by Barbery** [yryz/httpproxy#7]
![image](https://user-images.githubusercontent.com/2239529/62004481-41c24580-b158-11e9-8ac2-6a2971710dd0.png)
如图所示，运行超过24小时后，内存占用率飙升

**Comment by yryz** [comment]
多少连接量，使用端关闭后有降么

**Comment by Barbery** [comment]
后面定位到是client长连接的锅，和httpproxy无关
